name: lifx_http_api
description: A dart implementation of the LIFX HTTP API for smart LED bulbs.
version: 0.0.11+1
homepage: https://github.com/nathanielgreen/lifx_http_api
repository: https://github.com/nathanielgreen/lifx_http_api

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cli_repl: ^0.2.2
  dotenv: ^3.0.0
  http: ^0.13.3
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  lint: ^1.5.3
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.1.0
  test: ^1.17.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
